### ISSUE TITLE
Falta actividad 15

### ISSUE THREAD

**Issue by vcuspinera** [m5991/hello#3]
@m5991 y @CesarMedina95 veo que hicieron el branch pero falta hacer el pull request, para más referencia revisar las secciones 2 y 3 de la [actividad 15](https://github.com/vcuspinera/UDG_MCD_Project_Dev_II/blob/main/actividades/15_GitHub_teams.md).

Saludos,
Víctor

**Comment by m5991** [comment]
Buenas tardes, Mtro.

Ya añadí el branch creado por Cesar como Pull request. 
Gracias.
